// Full real IIFE; capture Chrome/runtime and window/message listeners.
// DOM is detached/inert. Script tags are observed but never executed as MAIN-world code.
async function contentFixture(html,win){
    var doc=new DOMParser().parseFromString(html||'<html><head></head><body></body></html>','text/html');
    var listeners=[],messages=[],effects=[],scripts=[];
    var w=win||{location:{href:'https://fixture.invalid',reload:function(){effects.push('reload');}},history:{back:function(){effects.push('back');},forward:function(){effects.push('forward');}},innerWidth:800,innerHeight:600};
    w.addEventListener=function(type,fn){if(type!=='message')throw new Error('unexpected event '+type);messages.push(fn);};
    w.HTMLInputElement=HTMLInputElement;w.HTMLTextAreaElement=HTMLTextAreaElement;
    var originalCreate=doc.createElement.bind(doc);doc.createElement=function(tag){var el=originalCreate(tag);if(tag==='script')scripts.push(el);return el;};
    var globals={window:w,document:doc,Event:Event,KeyboardEvent:KeyboardEvent,chrome:{runtime:{onMessage:{addListener:function(fn){listeners.push(fn);}}}},MouseEvent:function(type,opts){return new MouseEvent(type,Object.assign({},opts,{view:null}));}};
    var m=await loadModules(['src/platform/extension/content-script.js'],{globals:globals});
    return {doc:doc,win:w,listeners:listeners,messages:messages,effects:effects,scripts:scripts,m:m,globals:globals,
        action:function(action,args){var replies=[];var keep=listeners[0]({type:'browser-action',action:action,args:args||{}},{},function(r){replies.push(r);});return {response:replies[0],replies:replies,keep:keep};},
        post:function(data,source){messages[0]({source:source===undefined?w:source,data:data});}};
}
describe('content script real dispatch',function(){
    test('installs once, ignores foreign message type, and reports unknown actions',async function(){
        var f=await contentFixture();assert.strictEqual(f.listeners.length,1);assert.strictEqual(f.messages.length,1);assert.strictEqual(f.scripts.length,1);assert.strictEqual(f.win.__appagentContentScriptInjected,true);
        await loadModules(['src/platform/extension/content-script.js'],{globals:f.globals});assert.strictEqual(f.listeners.length,1);assert.strictEqual(f.scripts.length,1);
        var responses=[];assert.strictEqual(f.listeners[0]({type:'unrelated'},{},function(r){responses.push(r);}),undefined);assert.deepStrictEqual(responses,[]);
        assert.deepStrictEqual(f.action('unknown').response,{error:'Unknown action: unknown'});assert.deepStrictEqual(f.m.__unstubbed,[]);
    });
    test('page info and navigation route to browser effects exactly once',async function(){var f=await contentFixture('<title>Fixture</title>');assert.deepStrictEqual(f.action('get_page_info').response,{success:true,url:'https://fixture.invalid',title:'Fixture',viewportWidth:800,viewportHeight:600});['go_back','go_forward','reload'].forEach(function(a){assert.strictEqual(f.action(a).response.success,true);});assert.deepStrictEqual(f.effects,['back','forward','reload']);});
    test('nested gsft_main supplies inner DOM and URL but keeps outer title',async function(){
        var f=await contentFixture('<title>Outer</title><iframe id="gsft_main"></iframe>'),inner=new DOMParser().parseFromString('<p>Inner</p>','text/html'),frame=f.doc.getElementById('gsft_main');
        Object.defineProperty(frame,'contentDocument',{value:inner});Object.defineProperty(frame,'contentWindow',{value:{location:{href:'https://fixture.invalid/inner'}}});
        assert.match(f.action('get_dom').response.html,/<p>Inner<\/p>/);assert.strictEqual(f.action('get_page_info').response.url,'https://fixture.invalid/inner');assert.strictEqual(f.action('get_page_info').response.title,'Outer');
    });
    test('cross-origin gsft_main access falls back instead of throwing',async function(){var f=await contentFixture('<p>Outer</p><iframe id="gsft_main"></iframe>'),frame=f.doc.getElementById('gsft_main');Object.defineProperty(frame,'contentDocument',{get:function(){throw new Error('cross-origin');}});Object.defineProperty(frame,'contentWindow',{get:function(){throw new Error('cross-origin');}});assert.match(f.action('get_dom').response.html,/<p>Outer<\/p>/);assert.strictEqual(f.action('get_page_info').response.url,'https://fixture.invalid');});
    test('get_dom validates selectors, returns indexed match count and truncates',async function(){
        var f=await contentFixture('<div class="item">One</div><div class="item">Two</div>');var r=f.action('get_dom',{selector:'.item',match_index:1,max_length:12}).response;assert.strictEqual(r.match_count,2);assert.strictEqual(r.html,'<div class="\n... [truncated]');
        var missing=f.action('get_dom',{selector:'.item',match_index:2}).response;assert.strictEqual(missing.success,false);assert.strictEqual(missing.match_count,2);assert.match(missing.error,/match_index=2/);assert.match(f.action('get_dom',{selector:'['}).response.error,/Invalid CSS selector/);
    });
    test('get_dom discovers matches inside open shadow roots',async function(){var f=await contentFixture('<div class="target">Light</div><section id="host"></section>'),host=f.doc.getElementById('host');host.attachShadow({mode:'open'}).innerHTML='<span class="target">Shadow</span>';var r=f.action('get_dom',{selector:'.target',match_index:1}).response;assert.strictEqual(r.match_count,2);assert.strictEqual(r.html,'<span class="target">Shadow</span>');});
    test('fill prefers open modal, bypasses value tracker and emits user-input chain',async function(){
        var f=await contentFixture('<input class="target" value="background"><dialog open><input class="target"></dialog>'),el=f.doc.querySelector('dialog input'),events=[],focused=0,scrolled=0;
        var trackedWrites=0,nativeValue=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');Object.defineProperty(el,'value',{get:function(){return nativeValue.get.call(this);},set:function(){trackedWrites++;}});
        el.focus=function(){focused++;};el.scrollIntoView=function(){scrolled++;};['keydown','keypress','input','keyup','change'].forEach(function(type){el.addEventListener(type,function(e){events.push([e.type,e.bubbles,e.key||null]);});});
        var r=f.action('fill',{selector:'.target',value:'Hello!'});assert.strictEqual(r.keep,true);assert.strictEqual(r.response.success,true);assert.strictEqual(el.value,'Hello!');assert.strictEqual(trackedWrites,0);assert.strictEqual(f.doc.querySelector('input').value,'background');assert.strictEqual(focused,1);assert.strictEqual(scrolled,1);assert.deepStrictEqual(events.map(function(x){return x[0];}),['keydown','keypress','input','keyup','change']);assert.strictEqual(events[0][2],'!');assert.ok(events.every(function(x){return x[1];}));
    });
    test('select_option chooses by text and emits change only on a match',async function(){var f=await contentFixture('<select id="s"><option value="a">Alpha</option><option value="b">Beta</option></select>'),el=f.doc.getElementById('s'),events=0;el.addEventListener('change',function(){events++;});var r=f.action('select_option',{selector:'#s',text:'Beta'}).response;assert.deepStrictEqual([r.selectedValue,r.selectedText],['b','Beta']);assert.strictEqual(el.value,'b');var missing=f.action('select_option',{selector:'#s',value:'missing'}).response;assert.deepStrictEqual(missing.availableOptions,[{value:'a',text:'Alpha'},{value:'b',text:'Beta'}]);assert.strictEqual(events,1);});
    test('dispatch rejects missing/unknown event and missing target without effects',async function(){var f=await contentFixture('<button id="b">B</button>'),count=0;f.doc.getElementById('b').addEventListener('click',function(){count++;});assert.match(f.action('dispatch_event',{selector:'#b'}).response.error,/required/);assert.match(f.action('dispatch_event',{selector:'#b',event:'error'}).response.error,/not allowed/);assert.match(f.action('dispatch_event',{selector:'#missing',event:'click'}).response.error,/Element not found/);assert.strictEqual(count,0);});
    test('mouseenter emits non-bubbling mouse event followed by bubbling compatibility event',async function(){var f=await contentFixture('<button id="b">B</button>'),el=f.doc.getElementById('b'),events=[];el.getBoundingClientRect=function(){return {left:10,top:20,width:20,height:40};};['mouseenter','mouseover'].forEach(function(t){el.addEventListener(t,function(e){events.push(e);});});assert.strictEqual(f.action('dispatch_event',{selector:'#b',event:'mouseenter'}).response.success,true);assert.deepStrictEqual(events.map(function(e){return [e.type,e.bubbles];}),[['mouseenter',false],['mouseover',true]]);assert.ok(events[0] instanceof MouseEvent);assert.deepStrictEqual([events[0].clientX,events[0].clientY],[20,40]);});
    test('console collection rejects foreign windows, caps at 100 and drains',async function(){var f=await contentFixture();f.post({type:'appagent-console',level:'log',message:'foreign'},{});for(var i=0;i<105;i++)f.post({type:'appagent-console',level:'warn',message:String(i)});var logs=f.action('get_console_logs').response.logs;assert.strictEqual(logs.length,100);assert.strictEqual(logs[0].message,'5');assert.strictEqual(logs[99].level,'warn');assert.strictEqual(typeof logs[0].timestamp,'number');assert.deepStrictEqual(f.action('get_console_logs').response.logs,[]);});
    test('network collection keeps failure status and drains independently from console',async function(){var f=await contentFixture();f.post({type:'appagent-console',level:'error',message:'still here'});for(var i=0;i<101;i++)f.post({type:'appagent-network',method:'POST',url:'https://fixture.invalid/'+i,status:0,duration:i});var r=f.action('get_network_requests').response.requests;assert.strictEqual(r.length,100);assert.strictEqual(r[0].url,'https://fixture.invalid/1');assert.strictEqual(r[99].status,0);assert.strictEqual(r[99].duration,100);assert.deepStrictEqual(f.action('get_network_requests').response.requests,[]);assert.strictEqual(f.action('get_console_logs').response.logs.length,1);});
    test('viewport style is created, updated in place and removed',async function(){var f=await contentFixture();assert.strictEqual(f.action('viewport_emulate',{enable:true,width:400}).response.success,true);var el=f.doc.getElementById('__appagent_viewport_emulate');assert.match(el.textContent,/400px/);f.action('viewport_emulate',{enable:true,width:600});assert.strictEqual(f.doc.querySelectorAll('#__appagent_viewport_emulate').length,1);assert.match(el.textContent,/600px/);f.action('viewport_emulate',{enable:false});assert.strictEqual(f.doc.getElementById('__appagent_viewport_emulate'),null);});
});
